[package]
name = "axum-simd-json"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8", features = ["json"] }
axum-core = "0.5"
bytes = "1.9"
http = "1.2"
mime = "0.3"
simd-json-derive = "0.15"

[dev-dependencies]
simd-json = "0.14"
